export default [
    {
        id: 1,
        country: "Portugal",
        photo: "https://www.deboanatrip.com/wp-content/uploads/2020/08/praiadonaana-38-768x576.jpg",
        attraction: "Lagos",
        beginDate: "10 April, 2022",
        finishDate: "15 April, 2022",
        description: "In 2014 win the best beach in the world.",
        maps:"https://goo.gl/maps/qncp9wM5SeD8j43R6"
    },
    {
        id: 2,
        country: "Netherlands",
        photo: "https://www.aproximaviagem.pt/wp-content/uploads/2019/10/Eindhoven-e-uma-cidade-com-construcoes-futuristas.jpg",
        attraction: "Eidhoven",
        beginDate: "4 June, 2022",
        finishDate: "5 June, 2022",
        description: "To visit Pedro that is in Erasmus",
        maps:"https://goo.gl/maps/vD5sW4DiyoEERcjG8",
    },
    {
        id: 3,
        country: "Germany",
        photo: "https://cdn.britannica.com/73/12273-050-31C39284/Steeples-Reinoldikirche-Marienkirche-Alter-Markt-Dortmund-city.jpg",
        attraction: "Dortmund",
        beginDate: "2 June, 2022",
        finishDate: "3 June, 2022",
        description: "To visit Pedro that is in Erasmus",
        maps:"https://goo.gl/maps/9VynnJBXR6UB8ckQ9",
    },
    {
        id: 4,
        country: "Portugal",
        photo: "https://d5c6u7j9.stackpathcdn.com/wp-content/uploads/2019/04/Tavira-from-the-air.jpg",
        attraction: "Tavira",
        beginDate: "2 February, 2022",
        finishDate: "3 February, 2022",
        description: "Beautiful day with my mother and stepfather.",
        maps:"https://goo.gl/maps/9VynnJBXR6UB8ckQ9",
    },
    {
        id: 5,
        country: "Portugal",
        photo: "https://d5c6u7j9.stackpathcdn.com/wp-content/uploads/2019/04/Tavira-from-the-air.jpg",
        attraction: "Sagres",
        beginDate: "2 February, 2022",
        finishDate: "3 February, 2022",
        description: "Beautiful day with my mother and stepfather.",
        maps:"https://goo.gl/maps/9VynnJBXR6UB8ckQ9",
    },
    {
        id: 6,
        country: "Portugal",
        photo: "https://d5c6u7j9.stackpathcdn.com/wp-content/uploads/2019/04/Tavira-from-the-air.jpg",
        attraction: "Quarteira",
        beginDate: "2 February, 2022",
        finishDate: "3 February, 2022",
        description: "Beautiful day with my mother and stepfather.",
        maps:"https://goo.gl/maps/9VynnJBXR6UB8ckQ9",
    },
    {
        id: 7,
        country: "Portugal",
        photo: "https://d5c6u7j9.stackpathcdn.com/wp-content/uploads/2019/04/Tavira-from-the-air.jpg",
        attraction: "Aveiro",
        beginDate: "2 February, 2022",
        finishDate: "3 February, 2022",
        description: "Beautiful day with my mother and stepfather.",
        maps:"https://goo.gl/maps/9VynnJBXR6UB8ckQ9",
    },
    {
        id: 8,
        country: "Portugal",
        photo: "https://d5c6u7j9.stackpathcdn.com/wp-content/uploads/2019/04/Tavira-from-the-air.jpg",
        attraction: "Porto",
        beginDate: "2 February, 2022",
        finishDate: "3 February, 2022",
        description: "Beautiful day with my mother and stepfather.",
        maps:"https://goo.gl/maps/9VynnJBXR6UB8ckQ9",
    },
]